# paths to bam files
paths:
  control-1: &control-1 /path/to/bam/file/control-1.bam
  mutant-1: &mutant-1 /path/to/bam/file/mutant-1.bam
  mutant-2: &mutant-2 /path/to/bam/file/mutant-2.bam

# path to bed file for varying window sizes (optional)
bed_path: /path/to/bed/file.bed

# comparisons to be analyzed
comparisons:
  control-1-vs-mutant-1:
    control: *control-1
    mutant: *mutant-1
  control-1-vs-mutant-2:
    control: *control-1
    mutant: *mutant-2

# list of chromosomes to be analyzed
chromosomes: Chromosome1, Chromosome2, Chromosome3, AnotherChromosome

# paramters for CNV/window size calculations (defaults are shown)
parameters:
  annotate: TRUE
  bed_file: FALSE
  bigger: 1.5
  log2: 0.6
  pvalue: 0.001
  window_size: 10000
