#name: cnv-seq
channels:
  - defaults
  - bioconda
  - conda-forge
  - r
  - pcgr
dependencies:
  - jupyter
  - r-base
  #- r-irkernel
  #- r-devtools
  #- r-configr
  #- r-biocmanager
  #- bioconductor-genomicalignments
