dependencies:
  - conda-forge::notebook
  - r::rstudio
  - r::r-irkernel
  - r::r-essentials
  - conda-forge::r-devtools
  - pcgr::r-configr
  - conda-forge::r-biocmanager
  - bioconda::bioconductor-genomicalignments
