name: cnv-seq-test
channels:
  - defaults
  - bioconda
  - conda-forge
  - r
  - pcgr
dependencies:
  - jupyter
  - r-base=4.0
  - r-irkernel
  - r-devtools
  - r-configr
  - r-biocmanager
  - bioconductor-genomicalignments
